apiVersion: v1
kind: Service
metadata:
  name: backend-service-2022bcd0026
spec:
  selector:
    app: backend
    owner: 2022bcd0026
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001  # Optional: Specify a NodePort (or let Kubernetes assign one)
  type: NodePort