apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-byisrar
spec:
  replicas: 2
  selector:
    matchLabels:
      tag: backend
  template:
    metadata:
      labels:
        tag: backend
    spec:
      containers:
      - name: backend
        image: byisrar/mybackend:byisrar
        imagePullPolicy: IfNotPresent
        ports :
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PASSWORD
