apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-2022bcd0026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      owner: 2022bcd0026
  template:
    metadata:
      labels:
        app: backend
        owner: 2022bcd0026
    spec:
      containers:
      - name: backend
        image: bhanureddy1973/2022bcd0026-bhanu-reddy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PASSWORD