version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-2022bcd0026
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasksdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Backend
  backend:
    image: 2022bcd0026-bhanu-reddy:latest
    container_name: backend-2022bcd0026
    restart: unless-stopped
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: tasksdb
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  # React Frontend
  frontend:
    image: frontend-2022bcd0026-bhanu-reddy:latest
    container_name: frontend-2022bcd0026
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local