apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: frontend
  template:
    metadata:
      labels:
        tag: frontend
    spec:
      containers:
        - name: frontend-container
          image: byisrar/myfrontend:byisrar
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_API_URL

