apiVersion: v1
kind: Service
metadata:
  name: frontend-service-2022bcd0026
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort