apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2022bcd0026
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"