apiVersion: v1
kind: Service
metadata:
  name: mysql-2022bcd0026
spec:
  selector:
    app: mysql
    owner: 2022bcd0026
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
