apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-2022bcd0026
spec:
  selector:
    matchLabels:
      app: mysql
      owner: 2022bcd0026
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        owner: 2022bcd0026
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-2022bcd0026
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config-2022bcd0026
              key: DB_NAME
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-2022bcd0026
      - name: init-script
        configMap:
          name: mysql-init-script
